/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockxbee_usart.h"

static const char* CMockString_initialise_XBee_USART = "initialise_XBee_USART";
static const char* CMockString_xbee_usart_IsRxReady = "xbee_usart_IsRxReady";
static const char* CMockString_xbee_usart_IsTxReady = "xbee_usart_IsTxReady";
static const char* CMockString_xbee_usart_SendFrame = "xbee_usart_SendFrame";
static const char* CMockString_xbee_usart_build_frame = "xbee_usart_build_frame";
static const char* CMockString_xbee_usart_wait_for_ack = "xbee_usart_wait_for_ack";

typedef struct _CMOCK_initialise_XBee_USART_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_initialise_XBee_USART_CALL_INSTANCE;

typedef struct _CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE;

typedef struct _CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE;

typedef struct _CMOCK_xbee_usart_SendFrame_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  XBEE_USART_STATE_T ReturnVal;

} CMOCK_xbee_usart_SendFrame_CALL_INSTANCE;

typedef struct _CMOCK_xbee_usart_build_frame_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  XBEE_USART_STATE_T ReturnVal;

} CMOCK_xbee_usart_build_frame_CALL_INSTANCE;

typedef struct _CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  XBEE_USART_STATE_T ReturnVal;

} CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE;

static struct Mockxbee_usartInstance
{
  CMOCK_MEM_INDEX_TYPE initialise_XBee_USART_CallInstance;
  CMOCK_MEM_INDEX_TYPE xbee_usart_IsRxReady_CallInstance;
  CMOCK_MEM_INDEX_TYPE xbee_usart_IsTxReady_CallInstance;
  CMOCK_MEM_INDEX_TYPE xbee_usart_SendFrame_CallInstance;
  CMOCK_MEM_INDEX_TYPE xbee_usart_build_frame_CallInstance;
  CMOCK_MEM_INDEX_TYPE xbee_usart_wait_for_ack_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockxbee_usart_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.initialise_XBee_USART_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_initialise_XBee_USART);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.xbee_usart_IsRxReady_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xbee_usart_IsRxReady);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.xbee_usart_IsTxReady_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xbee_usart_IsTxReady);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.xbee_usart_SendFrame_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xbee_usart_SendFrame);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.xbee_usart_build_frame_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xbee_usart_build_frame);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.xbee_usart_wait_for_ack_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xbee_usart_wait_for_ack);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockxbee_usart_Init(void)
{
  Mockxbee_usart_Destroy();
}

void Mockxbee_usart_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void initialise_XBee_USART(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initialise_XBee_USART_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_initialise_XBee_USART);
  cmock_call_instance = (CMOCK_initialise_XBee_USART_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initialise_XBee_USART_CallInstance);
  Mock.initialise_XBee_USART_CallInstance = CMock_Guts_MemNext(Mock.initialise_XBee_USART_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void initialise_XBee_USART_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initialise_XBee_USART_CALL_INSTANCE));
  CMOCK_initialise_XBee_USART_CALL_INSTANCE* cmock_call_instance = (CMOCK_initialise_XBee_USART_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.initialise_XBee_USART_CallInstance = CMock_Guts_MemChain(Mock.initialise_XBee_USART_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

bool xbee_usart_IsRxReady(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xbee_usart_IsRxReady);
  cmock_call_instance = (CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xbee_usart_IsRxReady_CallInstance);
  Mock.xbee_usart_IsRxReady_CallInstance = CMock_Guts_MemNext(Mock.xbee_usart_IsRxReady_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xbee_usart_IsRxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE));
  CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_xbee_usart_IsRxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xbee_usart_IsRxReady_CallInstance = CMock_Guts_MemChain(Mock.xbee_usart_IsRxReady_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool xbee_usart_IsTxReady(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xbee_usart_IsTxReady);
  cmock_call_instance = (CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xbee_usart_IsTxReady_CallInstance);
  Mock.xbee_usart_IsTxReady_CallInstance = CMock_Guts_MemNext(Mock.xbee_usart_IsTxReady_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xbee_usart_IsTxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE));
  CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_xbee_usart_IsTxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xbee_usart_IsTxReady_CallInstance = CMock_Guts_MemChain(Mock.xbee_usart_IsTxReady_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

XBEE_USART_STATE_T xbee_usart_SendFrame(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xbee_usart_SendFrame_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xbee_usart_SendFrame);
  cmock_call_instance = (CMOCK_xbee_usart_SendFrame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xbee_usart_SendFrame_CallInstance);
  Mock.xbee_usart_SendFrame_CallInstance = CMock_Guts_MemNext(Mock.xbee_usart_SendFrame_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xbee_usart_SendFrame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xbee_usart_SendFrame_CALL_INSTANCE));
  CMOCK_xbee_usart_SendFrame_CALL_INSTANCE* cmock_call_instance = (CMOCK_xbee_usart_SendFrame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xbee_usart_SendFrame_CallInstance = CMock_Guts_MemChain(Mock.xbee_usart_SendFrame_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(XBEE_USART_STATE_T[sizeof(cmock_to_return) == sizeof(XBEE_USART_STATE_T) ? 1 : -1])); /* add XBEE_USART_STATE_T to :treat_as_array if this causes an error */
}

XBEE_USART_STATE_T xbee_usart_build_frame(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xbee_usart_build_frame_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xbee_usart_build_frame);
  cmock_call_instance = (CMOCK_xbee_usart_build_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xbee_usart_build_frame_CallInstance);
  Mock.xbee_usart_build_frame_CallInstance = CMock_Guts_MemNext(Mock.xbee_usart_build_frame_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xbee_usart_build_frame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xbee_usart_build_frame_CALL_INSTANCE));
  CMOCK_xbee_usart_build_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_xbee_usart_build_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xbee_usart_build_frame_CallInstance = CMock_Guts_MemChain(Mock.xbee_usart_build_frame_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(XBEE_USART_STATE_T[sizeof(cmock_to_return) == sizeof(XBEE_USART_STATE_T) ? 1 : -1])); /* add XBEE_USART_STATE_T to :treat_as_array if this causes an error */
}

XBEE_USART_STATE_T xbee_usart_wait_for_ack(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xbee_usart_wait_for_ack);
  cmock_call_instance = (CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xbee_usart_wait_for_ack_CallInstance);
  Mock.xbee_usart_wait_for_ack_CallInstance = CMock_Guts_MemNext(Mock.xbee_usart_wait_for_ack_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xbee_usart_wait_for_ack_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE));
  CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE* cmock_call_instance = (CMOCK_xbee_usart_wait_for_ack_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xbee_usart_wait_for_ack_CallInstance = CMock_Guts_MemChain(Mock.xbee_usart_wait_for_ack_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(XBEE_USART_STATE_T[sizeof(cmock_to_return) == sizeof(XBEE_USART_STATE_T) ? 1 : -1])); /* add XBEE_USART_STATE_T to :treat_as_array if this causes an error */
}

