/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKXBEE_USART_H
#define _MOCKXBEE_USART_H

#include "../cmock/src/unity.h"
#include "../xbee_usart.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockxbee_usart_Init(void);
void Mockxbee_usart_Destroy(void);
void Mockxbee_usart_Verify(void);




#define initialise_XBee_USART_Expect() initialise_XBee_USART_CMockExpect(__LINE__)
void initialise_XBee_USART_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define xbee_usart_IsRxReady_ExpectAndReturn(cmock_retval) xbee_usart_IsRxReady_CMockExpectAndReturn(__LINE__, cmock_retval)
void xbee_usart_IsRxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define xbee_usart_IsTxReady_ExpectAndReturn(cmock_retval) xbee_usart_IsTxReady_CMockExpectAndReturn(__LINE__, cmock_retval)
void xbee_usart_IsTxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define xbee_usart_SendFrame_ExpectAndReturn(cmock_retval) xbee_usart_SendFrame_CMockExpectAndReturn(__LINE__, cmock_retval)
void xbee_usart_SendFrame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return);
#define xbee_usart_build_frame_ExpectAndReturn(cmock_retval) xbee_usart_build_frame_CMockExpectAndReturn(__LINE__, cmock_retval)
void xbee_usart_build_frame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return);
#define xbee_usart_wait_for_ack_ExpectAndReturn(cmock_retval) xbee_usart_wait_for_ack_CMockExpectAndReturn(__LINE__, cmock_retval)
void xbee_usart_wait_for_ack_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, XBEE_USART_STATE_T cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
