/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../cmock/src/cmock.h"
#include "Mockusart0.h"

static const char* CMockString_USART0_DefaultRxIsrCb = "USART0_DefaultRxIsrCb";
static const char* CMockString_USART0_DefaultTxIsrCb = "USART0_DefaultTxIsrCb";
static const char* CMockString_USART0_Disable = "USART0_Disable";
static const char* CMockString_USART0_Enable = "USART0_Enable";
static const char* CMockString_USART0_EnableRx = "USART0_EnableRx";
static const char* CMockString_USART0_EnableTx = "USART0_EnableTx";
static const char* CMockString_USART0_GetData = "USART0_GetData";
static const char* CMockString_USART0_Initialize = "USART0_Initialize";
static const char* CMockString_USART0_IsRxReady = "USART0_IsRxReady";
static const char* CMockString_USART0_IsTxBusy = "USART0_IsTxBusy";
static const char* CMockString_USART0_IsTxDone = "USART0_IsTxDone";
static const char* CMockString_USART0_IsTxReady = "USART0_IsTxReady";
static const char* CMockString_USART0_Read = "USART0_Read";
static const char* CMockString_USART0_SetISRCb = "USART0_SetISRCb";
static const char* CMockString_USART0_SetRXISRCb = "USART0_SetRXISRCb";
static const char* CMockString_USART0_SetTXISRCb = "USART0_SetTXISRCb";
static const char* CMockString_USART0_Write = "USART0_Write";
static const char* CMockString_cb = "cb";
static const char* CMockString_data = "data";
static const char* CMockString_type = "type";

typedef struct _CMOCK_USART0_Initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_Initialize_CALL_INSTANCE;

typedef struct _CMOCK_USART0_Enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_Enable_CALL_INSTANCE;

typedef struct _CMOCK_USART0_EnableRx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_EnableRx_CALL_INSTANCE;

typedef struct _CMOCK_USART0_EnableTx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_EnableTx_CALL_INSTANCE;

typedef struct _CMOCK_USART0_Disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_Disable_CALL_INSTANCE;

typedef struct _CMOCK_USART0_GetData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_USART0_GetData_CALL_INSTANCE;

typedef struct _CMOCK_USART0_IsTxReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_USART0_IsTxReady_CALL_INSTANCE;

typedef struct _CMOCK_USART0_IsRxReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_USART0_IsRxReady_CALL_INSTANCE;

typedef struct _CMOCK_USART0_IsTxBusy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_USART0_IsTxBusy_CALL_INSTANCE;

typedef struct _CMOCK_USART0_IsTxDone_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_USART0_IsTxDone_CALL_INSTANCE;

typedef struct _CMOCK_USART0_Read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_USART0_Read_CALL_INSTANCE;

typedef struct _CMOCK_USART0_Write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_data;

} CMOCK_USART0_Write_CALL_INSTANCE;

typedef struct _CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE;

typedef struct _CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE;

typedef struct _CMOCK_USART0_SetISRCb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  usart_callback Expected_cb;
  usart0_cb_t Expected_type;

} CMOCK_USART0_SetISRCb_CALL_INSTANCE;

typedef struct _CMOCK_USART0_SetRXISRCb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  usart_callback Expected_cb;

} CMOCK_USART0_SetRXISRCb_CALL_INSTANCE;

typedef struct _CMOCK_USART0_SetTXISRCb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  usart_callback Expected_cb;

} CMOCK_USART0_SetTXISRCb_CALL_INSTANCE;

static struct Mockusart0Instance
{
  CMOCK_MEM_INDEX_TYPE USART0_Initialize_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_Enable_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_EnableRx_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_EnableTx_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_Disable_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_GetData_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_IsTxReady_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_IsRxReady_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_IsTxBusy_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_IsTxDone_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_Read_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_Write_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_DefaultRxIsrCb_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_DefaultTxIsrCb_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_SetISRCb_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_SetRXISRCb_CallInstance;
  CMOCK_MEM_INDEX_TYPE USART0_SetTXISRCb_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockusart0_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.USART0_Initialize_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_Initialize);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_Enable_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_Enable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_EnableRx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_EnableRx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_EnableTx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_EnableTx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_Disable_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_Disable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_GetData_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_GetData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_IsTxReady_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_IsTxReady);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_IsRxReady_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_IsRxReady);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_IsTxBusy_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_IsTxBusy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_IsTxDone_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_IsTxDone);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_Read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_Read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_Write_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_Write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_DefaultRxIsrCb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_DefaultRxIsrCb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_DefaultTxIsrCb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_DefaultTxIsrCb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_SetISRCb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_SetISRCb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_SetRXISRCb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_SetRXISRCb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.USART0_SetTXISRCb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_USART0_SetTXISRCb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockusart0_Init(void)
{
  Mockusart0_Destroy();
}

void Mockusart0_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void USART0_Initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_Initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_Initialize);
  cmock_call_instance = (CMOCK_USART0_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_Initialize_CallInstance);
  Mock.USART0_Initialize_CallInstance = CMock_Guts_MemNext(Mock.USART0_Initialize_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_Initialize_CALL_INSTANCE));
  CMOCK_USART0_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_Initialize_CallInstance = CMock_Guts_MemChain(Mock.USART0_Initialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_Enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_Enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_Enable);
  cmock_call_instance = (CMOCK_USART0_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_Enable_CallInstance);
  Mock.USART0_Enable_CallInstance = CMock_Guts_MemNext(Mock.USART0_Enable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_Enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_Enable_CALL_INSTANCE));
  CMOCK_USART0_Enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_Enable_CallInstance = CMock_Guts_MemChain(Mock.USART0_Enable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_EnableRx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_EnableRx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_EnableRx);
  cmock_call_instance = (CMOCK_USART0_EnableRx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_EnableRx_CallInstance);
  Mock.USART0_EnableRx_CallInstance = CMock_Guts_MemNext(Mock.USART0_EnableRx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_EnableRx_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_EnableRx_CALL_INSTANCE));
  CMOCK_USART0_EnableRx_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_EnableRx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_EnableRx_CallInstance = CMock_Guts_MemChain(Mock.USART0_EnableRx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_EnableTx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_EnableTx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_EnableTx);
  cmock_call_instance = (CMOCK_USART0_EnableTx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_EnableTx_CallInstance);
  Mock.USART0_EnableTx_CallInstance = CMock_Guts_MemNext(Mock.USART0_EnableTx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_EnableTx_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_EnableTx_CALL_INSTANCE));
  CMOCK_USART0_EnableTx_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_EnableTx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_EnableTx_CallInstance = CMock_Guts_MemChain(Mock.USART0_EnableTx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_Disable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_Disable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_Disable);
  cmock_call_instance = (CMOCK_USART0_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_Disable_CallInstance);
  Mock.USART0_Disable_CallInstance = CMock_Guts_MemNext(Mock.USART0_Disable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_Disable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_Disable_CALL_INSTANCE));
  CMOCK_USART0_Disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_Disable_CallInstance = CMock_Guts_MemChain(Mock.USART0_Disable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

uint8_t USART0_GetData(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_GetData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_GetData);
  cmock_call_instance = (CMOCK_USART0_GetData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_GetData_CallInstance);
  Mock.USART0_GetData_CallInstance = CMock_Guts_MemNext(Mock.USART0_GetData_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_GetData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_GetData_CALL_INSTANCE));
  CMOCK_USART0_GetData_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_GetData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_GetData_CallInstance = CMock_Guts_MemChain(Mock.USART0_GetData_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool USART0_IsTxReady(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_IsTxReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_IsTxReady);
  cmock_call_instance = (CMOCK_USART0_IsTxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_IsTxReady_CallInstance);
  Mock.USART0_IsTxReady_CallInstance = CMock_Guts_MemNext(Mock.USART0_IsTxReady_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_IsTxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_IsTxReady_CALL_INSTANCE));
  CMOCK_USART0_IsTxReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_IsTxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_IsTxReady_CallInstance = CMock_Guts_MemChain(Mock.USART0_IsTxReady_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool USART0_IsRxReady(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_IsRxReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_IsRxReady);
  cmock_call_instance = (CMOCK_USART0_IsRxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_IsRxReady_CallInstance);
  Mock.USART0_IsRxReady_CallInstance = CMock_Guts_MemNext(Mock.USART0_IsRxReady_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_IsRxReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_IsRxReady_CALL_INSTANCE));
  CMOCK_USART0_IsRxReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_IsRxReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_IsRxReady_CallInstance = CMock_Guts_MemChain(Mock.USART0_IsRxReady_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool USART0_IsTxBusy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_IsTxBusy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_IsTxBusy);
  cmock_call_instance = (CMOCK_USART0_IsTxBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_IsTxBusy_CallInstance);
  Mock.USART0_IsTxBusy_CallInstance = CMock_Guts_MemNext(Mock.USART0_IsTxBusy_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_IsTxBusy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_IsTxBusy_CALL_INSTANCE));
  CMOCK_USART0_IsTxBusy_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_IsTxBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_IsTxBusy_CallInstance = CMock_Guts_MemChain(Mock.USART0_IsTxBusy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool USART0_IsTxDone(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_IsTxDone_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_IsTxDone);
  cmock_call_instance = (CMOCK_USART0_IsTxDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_IsTxDone_CallInstance);
  Mock.USART0_IsTxDone_CallInstance = CMock_Guts_MemNext(Mock.USART0_IsTxDone_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_IsTxDone_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_IsTxDone_CALL_INSTANCE));
  CMOCK_USART0_IsTxDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_IsTxDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_IsTxDone_CallInstance = CMock_Guts_MemChain(Mock.USART0_IsTxDone_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint8_t USART0_Read(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_Read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_Read);
  cmock_call_instance = (CMOCK_USART0_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_Read_CallInstance);
  Mock.USART0_Read_CallInstance = CMock_Guts_MemNext(Mock.USART0_Read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void USART0_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_Read_CALL_INSTANCE));
  CMOCK_USART0_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_Read_CallInstance = CMock_Guts_MemChain(Mock.USART0_Read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void USART0_Write(const uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_Write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_Write);
  cmock_call_instance = (CMOCK_USART0_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_Write_CallInstance);
  Mock.USART0_Write_CallInstance = CMock_Guts_MemNext(Mock.USART0_Write_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_USART0_Write,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_USART0_Write(CMOCK_USART0_Write_CALL_INSTANCE* cmock_call_instance, const uint8_t data);
void CMockExpectParameters_USART0_Write(CMOCK_USART0_Write_CALL_INSTANCE* cmock_call_instance, const uint8_t data)
{
  cmock_call_instance->Expected_data = data;
}

void USART0_Write_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_Write_CALL_INSTANCE));
  CMOCK_USART0_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_Write_CallInstance = CMock_Guts_MemChain(Mock.USART0_Write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USART0_Write(cmock_call_instance, data);
}

void USART0_DefaultRxIsrCb(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_DefaultRxIsrCb);
  cmock_call_instance = (CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_DefaultRxIsrCb_CallInstance);
  Mock.USART0_DefaultRxIsrCb_CallInstance = CMock_Guts_MemNext(Mock.USART0_DefaultRxIsrCb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_DefaultRxIsrCb_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE));
  CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_DefaultRxIsrCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_DefaultRxIsrCb_CallInstance = CMock_Guts_MemChain(Mock.USART0_DefaultRxIsrCb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_DefaultTxIsrCb(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_DefaultTxIsrCb);
  cmock_call_instance = (CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_DefaultTxIsrCb_CallInstance);
  Mock.USART0_DefaultTxIsrCb_CallInstance = CMock_Guts_MemNext(Mock.USART0_DefaultTxIsrCb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void USART0_DefaultTxIsrCb_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE));
  CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_DefaultTxIsrCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_DefaultTxIsrCb_CallInstance = CMock_Guts_MemChain(Mock.USART0_DefaultTxIsrCb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USART0_SetISRCb(usart_callback cb, usart0_cb_t type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_SetISRCb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_SetISRCb);
  cmock_call_instance = (CMOCK_USART0_SetISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_SetISRCb_CallInstance);
  Mock.USART0_SetISRCb_CallInstance = CMock_Guts_MemNext(Mock.USART0_SetISRCb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_USART0_SetISRCb,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(usart_callback), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_USART0_SetISRCb,CMockString_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(usart0_cb_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_USART0_SetISRCb(CMOCK_USART0_SetISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb, usart0_cb_t type);
void CMockExpectParameters_USART0_SetISRCb(CMOCK_USART0_SetISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb, usart0_cb_t type)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(usart_callback[sizeof(cb) == sizeof(usart_callback) ? 1 : -1])); /* add usart_callback to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_type), (void*)(&type),
         sizeof(usart0_cb_t[sizeof(type) == sizeof(usart0_cb_t) ? 1 : -1])); /* add usart0_cb_t to :treat_as_array if this causes an error */
}

void USART0_SetISRCb_CMockExpect(UNITY_LINE_TYPE cmock_line, usart_callback cb, usart0_cb_t type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_SetISRCb_CALL_INSTANCE));
  CMOCK_USART0_SetISRCb_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_SetISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_SetISRCb_CallInstance = CMock_Guts_MemChain(Mock.USART0_SetISRCb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USART0_SetISRCb(cmock_call_instance, cb, type);
}

void USART0_SetRXISRCb(usart_callback cb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_SetRXISRCb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_SetRXISRCb);
  cmock_call_instance = (CMOCK_USART0_SetRXISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_SetRXISRCb_CallInstance);
  Mock.USART0_SetRXISRCb_CallInstance = CMock_Guts_MemNext(Mock.USART0_SetRXISRCb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_USART0_SetRXISRCb,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(usart_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_USART0_SetRXISRCb(CMOCK_USART0_SetRXISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb);
void CMockExpectParameters_USART0_SetRXISRCb(CMOCK_USART0_SetRXISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(usart_callback[sizeof(cb) == sizeof(usart_callback) ? 1 : -1])); /* add usart_callback to :treat_as_array if this causes an error */
}

void USART0_SetRXISRCb_CMockExpect(UNITY_LINE_TYPE cmock_line, usart_callback cb)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_SetRXISRCb_CALL_INSTANCE));
  CMOCK_USART0_SetRXISRCb_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_SetRXISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_SetRXISRCb_CallInstance = CMock_Guts_MemChain(Mock.USART0_SetRXISRCb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USART0_SetRXISRCb(cmock_call_instance, cb);
}

void USART0_SetTXISRCb(usart_callback cb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USART0_SetTXISRCb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_USART0_SetTXISRCb);
  cmock_call_instance = (CMOCK_USART0_SetTXISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USART0_SetTXISRCb_CallInstance);
  Mock.USART0_SetTXISRCb_CallInstance = CMock_Guts_MemNext(Mock.USART0_SetTXISRCb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_USART0_SetTXISRCb,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(usart_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_USART0_SetTXISRCb(CMOCK_USART0_SetTXISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb);
void CMockExpectParameters_USART0_SetTXISRCb(CMOCK_USART0_SetTXISRCb_CALL_INSTANCE* cmock_call_instance, usart_callback cb)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(usart_callback[sizeof(cb) == sizeof(usart_callback) ? 1 : -1])); /* add usart_callback to :treat_as_array if this causes an error */
}

void USART0_SetTXISRCb_CMockExpect(UNITY_LINE_TYPE cmock_line, usart_callback cb)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USART0_SetTXISRCb_CALL_INSTANCE));
  CMOCK_USART0_SetTXISRCb_CALL_INSTANCE* cmock_call_instance = (CMOCK_USART0_SetTXISRCb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.USART0_SetTXISRCb_CallInstance = CMock_Guts_MemChain(Mock.USART0_SetTXISRCb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USART0_SetTXISRCb(cmock_call_instance, cb);
}

