/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../cmock/src/cmock.h"
#include "Mocktwi0_master.h"

static const char* CMockString_I2C0_Close = "I2C0_Close";
static const char* CMockString_I2C0_Initialize = "I2C0_Initialize";
static const char* CMockString_I2C0_MasterOperation = "I2C0_MasterOperation";
static const char* CMockString_I2C0_MasterRead = "I2C0_MasterRead";
static const char* CMockString_I2C0_MasterWrite = "I2C0_MasterWrite";
static const char* CMockString_I2C0_Open = "I2C0_Open";
static const char* CMockString_I2C0_Poller = "I2C0_Poller";
static const char* CMockString_I2C0_SetAddress = "I2C0_SetAddress";
static const char* CMockString_I2C0_SetAddressNackCallback = "I2C0_SetAddressNackCallback";
static const char* CMockString_I2C0_SetBuffer = "I2C0_SetBuffer";
static const char* CMockString_I2C0_SetDataCompleteCallback = "I2C0_SetDataCompleteCallback";
static const char* CMockString_I2C0_SetDataNackCallback = "I2C0_SetDataNackCallback";
static const char* CMockString_I2C0_SetRestartReadCallback = "I2C0_SetRestartReadCallback";
static const char* CMockString_I2C0_SetRestartWriteCallback = "I2C0_SetRestartWriteCallback";
static const char* CMockString_I2C0_SetReturnResetCallback = "I2C0_SetReturnResetCallback";
static const char* CMockString_I2C0_SetReturnStopCallback = "I2C0_SetReturnStopCallback";
static const char* CMockString_I2C0_SetTimeout = "I2C0_SetTimeout";
static const char* CMockString_I2C0_SetTimeoutCallback = "I2C0_SetTimeoutCallback";
static const char* CMockString_I2C0_SetWriteCollisionCallback = "I2C0_SetWriteCollisionCallback";
static const char* CMockString_address = "address";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_bufferSize = "bufferSize";
static const char* CMockString_cb = "cb";
static const char* CMockString_funPtr = "funPtr";
static const char* CMockString_read = "read";
static const char* CMockString_to = "to";

typedef struct _CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_operations_t ReturnVal;
  void* Expected_funPtr;

} CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_operations_t ReturnVal;
  void* Expected_funPtr;

} CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_operations_t ReturnVal;
  void* Expected_funPtr;

} CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_operations_t ReturnVal;
  void* Expected_funPtr;

} CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_Initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_I2C0_Initialize_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_Open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_error_t ReturnVal;
  twi0_address_t Expected_address;

} CMOCK_I2C0_Open_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_Close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_error_t ReturnVal;

} CMOCK_I2C0_Close_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_MasterOperation_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_error_t ReturnVal;
  bool Expected_read;

} CMOCK_I2C0_MasterOperation_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_MasterWrite_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_error_t ReturnVal;

} CMOCK_I2C0_MasterWrite_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_MasterRead_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_error_t ReturnVal;

} CMOCK_I2C0_MasterRead_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetTimeout_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_to;

} CMOCK_I2C0_SetTimeout_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetBuffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_buffer;
  size_t Expected_bufferSize;

} CMOCK_I2C0_SetBuffer_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_callback_t Expected_cb;
  void* Expected_funPtr;

} CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_callback_t Expected_cb;
  void* Expected_funPtr;

} CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_callback_t Expected_cb;
  void* Expected_funPtr;

} CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_callback_t Expected_cb;
  void* Expected_funPtr;

} CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_callback_t Expected_cb;
  void* Expected_funPtr;

} CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_Poller_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_I2C0_Poller_CALL_INSTANCE;

typedef struct _CMOCK_I2C0_SetAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  twi0_address_t Expected_address;

} CMOCK_I2C0_SetAddress_CALL_INSTANCE;

static struct Mocktwi0_masterInstance
{
  CMOCK_MEM_INDEX_TYPE I2C0_SetReturnStopCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetReturnResetCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetRestartWriteCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetRestartReadCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_Initialize_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_Open_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_Close_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_MasterOperation_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_MasterWrite_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_MasterRead_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetTimeout_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetBuffer_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetDataCompleteCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetWriteCollisionCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetAddressNackCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetDataNackCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetTimeoutCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_Poller_CallInstance;
  CMOCK_MEM_INDEX_TYPE I2C0_SetAddress_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktwi0_master_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.I2C0_SetReturnStopCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetReturnStopCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetReturnResetCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetReturnResetCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetRestartWriteCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetRestartWriteCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetRestartReadCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetRestartReadCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_Initialize_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_Initialize);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_Open_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_Open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_Close_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_Close);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_MasterOperation_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_MasterOperation);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_MasterWrite_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_MasterWrite);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_MasterRead_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_MasterRead);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetTimeout_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetTimeout);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetBuffer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetBuffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetDataCompleteCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetDataCompleteCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetWriteCollisionCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetWriteCollisionCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetAddressNackCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetAddressNackCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetDataNackCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetDataNackCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetTimeoutCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetTimeoutCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_Poller_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_Poller);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.I2C0_SetAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_I2C0_SetAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktwi0_master_Init(void)
{
  Mocktwi0_master_Destroy();
}

void Mocktwi0_master_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

twi0_operations_t I2C0_SetReturnStopCallback(void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetReturnStopCallback);
  cmock_call_instance = (CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetReturnStopCallback_CallInstance);
  Mock.I2C0_SetReturnStopCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetReturnStopCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetReturnStopCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_SetReturnStopCallback(CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr);
void CMockExpectParameters_I2C0_SetReturnStopCallback(CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr)
{
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetReturnStopCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* funPtr, twi0_operations_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetReturnStopCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetReturnStopCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetReturnStopCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetReturnStopCallback(cmock_call_instance, funPtr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_operations_t[sizeof(cmock_to_return) == sizeof(twi0_operations_t) ? 1 : -1])); /* add twi0_operations_t to :treat_as_array if this causes an error */
}

twi0_operations_t I2C0_SetReturnResetCallback(void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetReturnResetCallback);
  cmock_call_instance = (CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetReturnResetCallback_CallInstance);
  Mock.I2C0_SetReturnResetCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetReturnResetCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetReturnResetCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_SetReturnResetCallback(CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr);
void CMockExpectParameters_I2C0_SetReturnResetCallback(CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr)
{
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetReturnResetCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* funPtr, twi0_operations_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetReturnResetCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetReturnResetCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetReturnResetCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetReturnResetCallback(cmock_call_instance, funPtr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_operations_t[sizeof(cmock_to_return) == sizeof(twi0_operations_t) ? 1 : -1])); /* add twi0_operations_t to :treat_as_array if this causes an error */
}

twi0_operations_t I2C0_SetRestartWriteCallback(void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetRestartWriteCallback);
  cmock_call_instance = (CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetRestartWriteCallback_CallInstance);
  Mock.I2C0_SetRestartWriteCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetRestartWriteCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetRestartWriteCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_SetRestartWriteCallback(CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr);
void CMockExpectParameters_I2C0_SetRestartWriteCallback(CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr)
{
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetRestartWriteCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* funPtr, twi0_operations_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetRestartWriteCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetRestartWriteCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetRestartWriteCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetRestartWriteCallback(cmock_call_instance, funPtr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_operations_t[sizeof(cmock_to_return) == sizeof(twi0_operations_t) ? 1 : -1])); /* add twi0_operations_t to :treat_as_array if this causes an error */
}

twi0_operations_t I2C0_SetRestartReadCallback(void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetRestartReadCallback);
  cmock_call_instance = (CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetRestartReadCallback_CallInstance);
  Mock.I2C0_SetRestartReadCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetRestartReadCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetRestartReadCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_SetRestartReadCallback(CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr);
void CMockExpectParameters_I2C0_SetRestartReadCallback(CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE* cmock_call_instance, void* funPtr)
{
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetRestartReadCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* funPtr, twi0_operations_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetRestartReadCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetRestartReadCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetRestartReadCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetRestartReadCallback(cmock_call_instance, funPtr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_operations_t[sizeof(cmock_to_return) == sizeof(twi0_operations_t) ? 1 : -1])); /* add twi0_operations_t to :treat_as_array if this causes an error */
}

uint8_t I2C0_Initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_Initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_Initialize);
  cmock_call_instance = (CMOCK_I2C0_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_Initialize_CallInstance);
  Mock.I2C0_Initialize_CallInstance = CMock_Guts_MemNext(Mock.I2C0_Initialize_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C0_Initialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_Initialize_CALL_INSTANCE));
  CMOCK_I2C0_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_Initialize_CallInstance = CMock_Guts_MemChain(Mock.I2C0_Initialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

twi0_error_t I2C0_Open(twi0_address_t address)
{
    
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_Open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_Open);
  cmock_call_instance = (CMOCK_I2C0_Open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_Open_CallInstance);
  Mock.I2C0_Open_CallInstance = CMock_Guts_MemNext(Mock.I2C0_Open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_Open,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(twi0_address_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  printf("I2C0_Open: Returning with %d\n", cmock_call_instance->ReturnVal );
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_Open(CMOCK_I2C0_Open_CALL_INSTANCE* cmock_call_instance, twi0_address_t address);
void CMockExpectParameters_I2C0_Open(CMOCK_I2C0_Open_CALL_INSTANCE* cmock_call_instance, twi0_address_t address)
{
  memcpy((void*)(&cmock_call_instance->Expected_address), (void*)(&address),
         sizeof(twi0_address_t[sizeof(address) == sizeof(twi0_address_t) ? 1 : -1])); /* add twi0_address_t to :treat_as_array if this causes an error */
}

void I2C0_Open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, twi0_address_t address, twi0_error_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_Open_CALL_INSTANCE));
  CMOCK_I2C0_Open_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_Open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_Open_CallInstance = CMock_Guts_MemChain(Mock.I2C0_Open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_Open(cmock_call_instance, address);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_error_t[sizeof(cmock_to_return) == sizeof(twi0_error_t) ? 1 : -1])); /* add twi0_error_t to :treat_as_array if this causes an error */
}

twi0_error_t I2C0_Close(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_Close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_Close);
  cmock_call_instance = (CMOCK_I2C0_Close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_Close_CallInstance);
  Mock.I2C0_Close_CallInstance = CMock_Guts_MemNext(Mock.I2C0_Close_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C0_Close_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, twi0_error_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_Close_CALL_INSTANCE));
  CMOCK_I2C0_Close_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_Close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_Close_CallInstance = CMock_Guts_MemChain(Mock.I2C0_Close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_error_t[sizeof(cmock_to_return) == sizeof(twi0_error_t) ? 1 : -1])); /* add twi0_error_t to :treat_as_array if this causes an error */
}

twi0_error_t I2C0_MasterOperation(bool read)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_MasterOperation_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_MasterOperation);
  cmock_call_instance = (CMOCK_I2C0_MasterOperation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_MasterOperation_CallInstance);
  Mock.I2C0_MasterOperation_CallInstance = CMock_Guts_MemNext(Mock.I2C0_MasterOperation_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_MasterOperation,CMockString_read);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_read, read, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2C0_MasterOperation(CMOCK_I2C0_MasterOperation_CALL_INSTANCE* cmock_call_instance, bool read);
void CMockExpectParameters_I2C0_MasterOperation(CMOCK_I2C0_MasterOperation_CALL_INSTANCE* cmock_call_instance, bool read)
{
  cmock_call_instance->Expected_read = read;
}

void I2C0_MasterOperation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool read, twi0_error_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_MasterOperation_CALL_INSTANCE));
  CMOCK_I2C0_MasterOperation_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_MasterOperation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_MasterOperation_CallInstance = CMock_Guts_MemChain(Mock.I2C0_MasterOperation_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_MasterOperation(cmock_call_instance, read);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_error_t[sizeof(cmock_to_return) == sizeof(twi0_error_t) ? 1 : -1])); /* add twi0_error_t to :treat_as_array if this causes an error */
}

twi0_error_t I2C0_MasterWrite(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_MasterWrite_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_MasterWrite);
  cmock_call_instance = (CMOCK_I2C0_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_MasterWrite_CallInstance);
  Mock.I2C0_MasterWrite_CallInstance = CMock_Guts_MemNext(Mock.I2C0_MasterWrite_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C0_MasterWrite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, twi0_error_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_MasterWrite_CALL_INSTANCE));
  CMOCK_I2C0_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_MasterWrite_CallInstance = CMock_Guts_MemChain(Mock.I2C0_MasterWrite_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_error_t[sizeof(cmock_to_return) == sizeof(twi0_error_t) ? 1 : -1])); /* add twi0_error_t to :treat_as_array if this causes an error */
}

twi0_error_t I2C0_MasterRead(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_MasterRead_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_MasterRead);
  cmock_call_instance = (CMOCK_I2C0_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_MasterRead_CallInstance);
  Mock.I2C0_MasterRead_CallInstance = CMock_Guts_MemNext(Mock.I2C0_MasterRead_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C0_MasterRead_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, twi0_error_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_MasterRead_CALL_INSTANCE));
  CMOCK_I2C0_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_MasterRead_CallInstance = CMock_Guts_MemChain(Mock.I2C0_MasterRead_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(twi0_error_t[sizeof(cmock_to_return) == sizeof(twi0_error_t) ? 1 : -1])); /* add twi0_error_t to :treat_as_array if this causes an error */
}

void I2C0_SetTimeout(uint8_t to)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetTimeout_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetTimeout);
  cmock_call_instance = (CMOCK_I2C0_SetTimeout_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetTimeout_CallInstance);
  Mock.I2C0_SetTimeout_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetTimeout_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetTimeout,CMockString_to);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_to, to, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetTimeout(CMOCK_I2C0_SetTimeout_CALL_INSTANCE* cmock_call_instance, uint8_t to);
void CMockExpectParameters_I2C0_SetTimeout(CMOCK_I2C0_SetTimeout_CALL_INSTANCE* cmock_call_instance, uint8_t to)
{
  cmock_call_instance->Expected_to = to;
}

void I2C0_SetTimeout_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t to)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetTimeout_CALL_INSTANCE));
  CMOCK_I2C0_SetTimeout_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetTimeout_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetTimeout_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetTimeout_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetTimeout(cmock_call_instance, to);
}

void I2C0_SetBuffer(void* buffer, size_t bufferSize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetBuffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetBuffer);
  cmock_call_instance = (CMOCK_I2C0_SetBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetBuffer_CallInstance);
  Mock.I2C0_SetBuffer_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetBuffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetBuffer,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetBuffer,CMockString_bufferSize);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bufferSize), (void*)(&bufferSize), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetBuffer(CMOCK_I2C0_SetBuffer_CALL_INSTANCE* cmock_call_instance, void* buffer, size_t bufferSize);
void CMockExpectParameters_I2C0_SetBuffer(CMOCK_I2C0_SetBuffer_CALL_INSTANCE* cmock_call_instance, void* buffer, size_t bufferSize)
{
  cmock_call_instance->Expected_buffer = buffer;
  memcpy((void*)(&cmock_call_instance->Expected_bufferSize), (void*)(&bufferSize),
         sizeof(size_t[sizeof(bufferSize) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void I2C0_SetBuffer_CMockExpect(UNITY_LINE_TYPE cmock_line, void* buffer, size_t bufferSize)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetBuffer_CALL_INSTANCE));
  CMOCK_I2C0_SetBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetBuffer_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetBuffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetBuffer(cmock_call_instance, buffer, bufferSize);
}

void I2C0_SetDataCompleteCallback(twi0_callback_t cb, void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetDataCompleteCallback);
  cmock_call_instance = (CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetDataCompleteCallback_CallInstance);
  Mock.I2C0_SetDataCompleteCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetDataCompleteCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetDataCompleteCallback,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(twi0_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetDataCompleteCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetDataCompleteCallback(CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr);
void CMockExpectParameters_I2C0_SetDataCompleteCallback(CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(twi0_callback_t[sizeof(cb) == sizeof(twi0_callback_t) ? 1 : -1])); /* add twi0_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetDataCompleteCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_callback_t cb, void* funPtr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetDataCompleteCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetDataCompleteCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetDataCompleteCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetDataCompleteCallback(cmock_call_instance, cb, funPtr);
}

void I2C0_SetWriteCollisionCallback(twi0_callback_t cb, void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetWriteCollisionCallback);
  cmock_call_instance = (CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetWriteCollisionCallback_CallInstance);
  Mock.I2C0_SetWriteCollisionCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetWriteCollisionCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetWriteCollisionCallback,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(twi0_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetWriteCollisionCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetWriteCollisionCallback(CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr);
void CMockExpectParameters_I2C0_SetWriteCollisionCallback(CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(twi0_callback_t[sizeof(cb) == sizeof(twi0_callback_t) ? 1 : -1])); /* add twi0_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetWriteCollisionCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_callback_t cb, void* funPtr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetWriteCollisionCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetWriteCollisionCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetWriteCollisionCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetWriteCollisionCallback(cmock_call_instance, cb, funPtr);
}

void I2C0_SetAddressNackCallback(twi0_callback_t cb, void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetAddressNackCallback);
  cmock_call_instance = (CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetAddressNackCallback_CallInstance);
  Mock.I2C0_SetAddressNackCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetAddressNackCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetAddressNackCallback,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(twi0_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetAddressNackCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetAddressNackCallback(CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr);
void CMockExpectParameters_I2C0_SetAddressNackCallback(CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(twi0_callback_t[sizeof(cb) == sizeof(twi0_callback_t) ? 1 : -1])); /* add twi0_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetAddressNackCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_callback_t cb, void* funPtr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetAddressNackCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetAddressNackCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetAddressNackCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetAddressNackCallback(cmock_call_instance, cb, funPtr);
}

void I2C0_SetDataNackCallback(twi0_callback_t cb, void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetDataNackCallback);
  cmock_call_instance = (CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetDataNackCallback_CallInstance);
  Mock.I2C0_SetDataNackCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetDataNackCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetDataNackCallback,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(twi0_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetDataNackCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetDataNackCallback(CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr);
void CMockExpectParameters_I2C0_SetDataNackCallback(CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(twi0_callback_t[sizeof(cb) == sizeof(twi0_callback_t) ? 1 : -1])); /* add twi0_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetDataNackCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_callback_t cb, void* funPtr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetDataNackCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetDataNackCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetDataNackCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetDataNackCallback(cmock_call_instance, cb, funPtr);
}

void I2C0_SetTimeoutCallback(twi0_callback_t cb, void* funPtr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetTimeoutCallback);
  cmock_call_instance = (CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetTimeoutCallback_CallInstance);
  Mock.I2C0_SetTimeoutCallback_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetTimeoutCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetTimeoutCallback,CMockString_cb);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(twi0_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetTimeoutCallback,CMockString_funPtr);
    if (cmock_call_instance->Expected_funPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(funPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_funPtr, funPtr, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetTimeoutCallback(CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr);
void CMockExpectParameters_I2C0_SetTimeoutCallback(CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE* cmock_call_instance, twi0_callback_t cb, void* funPtr)
{
  memcpy((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb),
         sizeof(twi0_callback_t[sizeof(cb) == sizeof(twi0_callback_t) ? 1 : -1])); /* add twi0_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_funPtr = funPtr;
}

void I2C0_SetTimeoutCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_callback_t cb, void* funPtr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE));
  CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetTimeoutCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetTimeoutCallback_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetTimeoutCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetTimeoutCallback(cmock_call_instance, cb, funPtr);
}

void I2C0_Poller(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_Poller_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_Poller);
  cmock_call_instance = (CMOCK_I2C0_Poller_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_Poller_CallInstance);
  Mock.I2C0_Poller_CallInstance = CMock_Guts_MemNext(Mock.I2C0_Poller_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void I2C0_Poller_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_Poller_CALL_INSTANCE));
  CMOCK_I2C0_Poller_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_Poller_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_Poller_CallInstance = CMock_Guts_MemChain(Mock.I2C0_Poller_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void I2C0_SetAddress(twi0_address_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_I2C0_SetAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_I2C0_SetAddress);
  cmock_call_instance = (CMOCK_I2C0_SetAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C0_SetAddress_CallInstance);
  Mock.I2C0_SetAddress_CallInstance = CMock_Guts_MemNext(Mock.I2C0_SetAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_I2C0_SetAddress,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(twi0_address_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C0_SetAddress(CMOCK_I2C0_SetAddress_CALL_INSTANCE* cmock_call_instance, twi0_address_t address);
void CMockExpectParameters_I2C0_SetAddress(CMOCK_I2C0_SetAddress_CALL_INSTANCE* cmock_call_instance, twi0_address_t address)
{
  memcpy((void*)(&cmock_call_instance->Expected_address), (void*)(&address),
         sizeof(twi0_address_t[sizeof(address) == sizeof(twi0_address_t) ? 1 : -1])); /* add twi0_address_t to :treat_as_array if this causes an error */
}

void I2C0_SetAddress_CMockExpect(UNITY_LINE_TYPE cmock_line, twi0_address_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C0_SetAddress_CALL_INSTANCE));
  CMOCK_I2C0_SetAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C0_SetAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C0_SetAddress_CallInstance = CMock_Guts_MemChain(Mock.I2C0_SetAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_I2C0_SetAddress(cmock_call_instance, address);
}

