/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../cmock/src/cmock.h"
#include "Mockeprom.h"

static const char* CMockString_eprom_read_serial_id = "eprom_read_serial_id";

typedef struct _CMOCK_eprom_read_serial_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* ReturnVal;

} CMOCK_eprom_read_serial_id_CALL_INSTANCE;

static struct MockepromInstance
{
  CMOCK_MEM_INDEX_TYPE eprom_read_serial_id_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockeprom_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.eprom_read_serial_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_eprom_read_serial_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockeprom_Init(void)
{
  Mockeprom_Destroy();
}

void Mockeprom_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint8_t* eprom_read_serial_id(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_eprom_read_serial_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_eprom_read_serial_id);
  cmock_call_instance = (CMOCK_eprom_read_serial_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.eprom_read_serial_id_CallInstance);
  Mock.eprom_read_serial_id_CallInstance = CMock_Guts_MemNext(Mock.eprom_read_serial_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void eprom_read_serial_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_eprom_read_serial_id_CALL_INSTANCE));
  CMOCK_eprom_read_serial_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_eprom_read_serial_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.eprom_read_serial_id_CallInstance = CMock_Guts_MemChain(Mock.eprom_read_serial_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

