/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKINA219_H
#define _MOCKINA219_H

#include "../unit/unity.h"
#include "../ina219/INA219.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockINA219_Init(void);
void MockINA219_Destroy(void);
void MockINA219_Verify(void);




#define INA219_Initialise_Expect(addr, profile) INA219_Initialise_CMockExpect(__LINE__, addr, profile)
void INA219_Initialise_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t addr, INA219_Config_Profile_t profile);
#define INA219_get_all_readings_ExpectAndReturn(cmock_retval) INA219_get_all_readings_CMockExpectAndReturn(__LINE__, cmock_retval)
void INA219_get_all_readings_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INA219_Data_t* cmock_to_return);
#define INA219_get_raw_reading_ExpectAndReturn(reading, cmock_retval) INA219_get_raw_reading_CMockExpectAndReturn(__LINE__, reading, cmock_retval)
void INA219_get_raw_reading_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INA219_Readings reading, uint16_t cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
