/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMODEM_H
#define _MOCKMODEM_H

#include "unity.h"
#include "modem.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockmodem_Init(void);
void Mockmodem_Destroy(void);
void Mockmodem_Verify(void);




#define modem_initialise_Expect(coordinator) modem_initialise_CMockExpect(__LINE__, coordinator)
void modem_initialise_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t coordinator);
#define modem_get_coord_addr_ExpectAndReturn(cmock_retval) modem_get_coord_addr_CMockExpectAndReturn(__LINE__, cmock_retval)
void modem_get_coord_addr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
